### ISSUE TITLE
Prodigy Hacks are patched! (they put an anticheat)

### ISSUE THREAD

**Issue by Ocenting** [PatheticMustan/ProdigyMathGameHacking#105]
Hi there, when I hit CTRL-SHIFT-I, it  seems that the game gets disconnected from the server.  Maybe they have a safeguard in place? (anti-cheat)

**Comment by ProdigyHacksDontWork** [comment]
Yeah, it's happening to me to, I hope they find a way to fix it.

**Comment by lil-sket** [comment]
uhhhhhhh i might have told 1 friend, then he told another friend, and another one, and another one

**Comment by Avn1114** [comment]
There is a way, look at the instructional video.

**Comment by DaChickenKing** [comment]
Also, I'm working on a new network-based cheat menu

**Comment by Avn1114** [comment]
They have, yes. Sent from Mail for Windows 10 From: OcentingSent: Saturday, March 28, 2020 3:24 PMTo: PatheticMustan/ProdigyMathGameHackingCc: SubscribedSubject: [PatheticMustan/ProdigyMathGameHacking] Prodigy Hacks are patched! (#105) Hi there, when I hit CTRL-SHIFT-I, it seems that the game gets disconnected from the server. Maybe they have a safeguard in place?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com

**Comment by ProdigyHacksDontWork** [comment]
Where is instructional video?

**Comment by Avn1114** [comment]
Check the Github README.md. Sent from Mail for Windows 10 From: ProdigyHacksDontWorkSent: Sunday, March 29, 2020 10:08 AMTo: PatheticMustan/ProdigyMathGameHackingCc: Arcerion; CommentSubject: Re: [PatheticMustan/ProdigyMathGameHacking] Prodigy Hacks are patched! (they put an anticheat) (#105) Where is instructional video?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com

**Comment by ProdigyHacksDontWork** [comment]
What is that exactly?

**Comment by Avn1114** [comment]
Like, the description on the homepage, when you scroll down.  From: ProdigyHacksDontWorkSent: Sunday, March 29, 2020 10:12 AMTo: PatheticMustan/ProdigyMathGameHackingCc: Arcerion; CommentSubject: Re: [PatheticMustan/ProdigyMathGameHacking] Prodigy Hacks are patched! (they put an anticheat) (#105) What is that exactly?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com

**Comment by ProdigyHacksDontWork** [comment]
Yup, it was very helpful. I downloaded Redirector, but I didn't get was it was for. Was I supposed to Ctrl Fn F5 when I opened Dev Tools? The {f:enableDebug} didn't work even though I put it in console. THIS IS TO COMPLICATED :(

**Comment by Ocenting** [comment]
I went to the Instructional Video, there was no description. :(

**Comment by Avn1114** [comment]
So sorry, the desc is only on the Discord… I’m taking down that vid.From: OcentingSent: Monday, March 30, 2020 1:26 PMTo: PatheticMustan/ProdigyMathGameHackingCc: Arcerion; CommentSubject: Re: [PatheticMustan/ProdigyMathGameHacking] Prodigy Hacks are patched! (they put an anticheat) (#105) I went to the Instructional Video, there was no description. :(—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com

**Comment by Magmischief** [comment]
Why is there like 5 issues for ¨Prodigy hacks are patched¨

**Comment by ProdigyHacksDontWork** [comment]
I CAN'T FIND THE VID ON DIS OR THIS SITE

**Comment by Diveodile** [comment]
I have the link: https://drive.google.com/file/d/1YN-6SYJSvNHv_YbmzUX603b_PYiylRKp/view
But you need to request access to the video.

**Comment by Diveodile** [comment]
> So sorry, the desc is only on the Discord… I’m taking down that vid.From: OcentingSent: Monday, March 30, 2020 1:26 PMTo: PatheticMustan/ProdigyMathGameHackingCc: Arcerion; CommentSubject: Re: [PatheticMustan/ProdigyMathGameHacking] Prodigy Hacks are patched! (they put an anticheat) (#105) I went to the Instructional Video, there was no description. :(—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.  Virus-free. [www.avg.com](http://www.avg.com)

Why do I keep seeing this kind of stuff.

**Comment by Diveodile** [comment]
> So sorry, the desc is only on the Discord… I’m taking down that vid.From: OcentingSent: Monday, March 30, 2020 1:26 PMTo: PatheticMustan/ProdigyMathGameHackingCc: Arcerion; CommentSubject: Re: [PatheticMustan/ProdigyMathGameHacking] Prodigy Hacks are patched! (they put an anticheat) (#105) I went to the Instructional Video, there was no description. :(—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.  Virus-free. [www.avg.com](http://www.avg.com)

Why do I keep seeing this kind of stuff?

**Comment by ProdigyHacksDontWork** [comment]
I found the vid. I've done it and I can edit console without leaving to play.prodigygame.com/play. Thank you a lot. Now new problem has arisen, none of the hacks work. Sez something about state not being defined

**Comment by RtypeX** [comment]
Crap, this is complicated.

**Comment by ProdigyHacksDontWork** [comment]
I found a new hack. Check My issue to see it

**Comment by Diveodile** [comment]
> I found the vid. I've done it and I can edit console without leaving to play.prodigygame.com/play. Thank you a lot. Now new problem has arisen, none of the hacks work. Sez something about state not being defined

You are welcome.

**Comment by RtypeX** [comment]
I can't find the desc.

**Comment by Diveodile** [comment]
The description is on their Discord server.
