### ISSUE TITLE
Admin Login???

### ISSUE THREAD

**Issue by Avn1114** [PatheticMustan/ProdigyMathGameHacking#23]
I found something that may be of some use: 
![image](https://user-images.githubusercontent.com/60945964/75450287-82777c80-593c-11ea-887c-340c05afdf4d.png)

**Comment by LaneLunsford** [comment]
I was typing in that code when it suggested instead of network I could do this 
                              PIXI.game.prodigy.achievements
I don't know if yall are already on to this or if this is new but u might could get all achievements I have no clue I'm the one who asked how to learn code on the game constants page so I'm still learning but u might be able to try this.

**Comment by Avn1114** [comment]
Yeah, I have looked into that, but I don't know the locators and keywords
necessary to actually achieve this.

**Comment by PatheticMustan** [comment]
From what I understand, admin login un-hides everything, allowing you to do A WHOLE LOT of interesting things.

**Comment by PatheticMustan** [comment]
PIXI.game.prodigy.network.adminLogin
