### ISSUE TITLE
Auto-skipping quests

### ISSUE THREAD

**Issue by Avn1114** [PatheticMustan/ProdigyMathGameHacking#6]
How would I go about finding a way to auto-skip quests?

**Comment by PatheticMustan** [comment]
What do you mean by auto skipping quests?

**Comment by PatheticMustan** [comment]
Do you mean completing bounties, or....

**Comment by Avn1114** [comment]
Like, completing Firefly forest, Shiverchill mt. etc. instantaneously

**Comment by PatheticMustan** [comment]
I did it! I'll explain how I figured it out to help you in future detective work.

**Comment by Avn1114** [comment]
Please do!

**Comment by PatheticMustan** [comment]
So first, just exploring around, we can find `PIXI.game.prodigy.debugQuests`.
Assuming that there is a way to complete quests in here, we look through the prototype to find

`PIXI.game.prodigy.debugQuests.completeQuestRequirements(t)`

Now we need to figure out what to put in for parameter `t`.
`completeQuestRequirements.toString()` returns
```
function (t){
var i=this.game.prodigy.world.zones[t],
n=i.getCurrentQuest(),
e=0;
if(l.b.isValid(n)){
var s=n.req;
if("item"===s.type)this.game.prodigy.player.backpack.add(s.type,s.ID,!1,l.b.isValid(s.N)?s.N:1);
else if("key"===s.type)this.game.prodigy.player.backpack.add(s.type,s.ID,!1,l.b.isValid(s.N)?s.N:1);
else if("pet"===s.type)for(e=0;e<s.N;e++)i.defeatMonster(s.ID,e,s.U);
else if("seq"===s.type)for(e=0;e<s.N;e++)i.completeSequence(n.ID,e)
}
}
```

Seeing that it sets `i` to  `PIXI.game.prodigy.world.zones[t]`, we  can assume that t is a key of object `PIXI.game.prodigy.world.zones`.

Now we need to figure out what keys are in `world.zones`.
`Object.keys(PIXI.game.prodigy.world.zones)`

```
object forest
object shiverchill
object skywatch
object lamplight
object dyno
object bonfire_spire
object house
object toyzone
object shipwreck_shore
object darktower
object academy
object archives
object earthtower
object tower_town
```

Since I was in Shiverchill, I did
`PIXI.game.prodigy.debugQuests.completeQuestRequirements("shiverchill")`, but nothing happened. I could no longer move, or interact with panels. (???)

On reloading the page, the quest was completed!

![B3B9F4F7-6289-4DC9-B619-71422B61FBD9](https://user-images.githubusercontent.com/35382971/74556994-346e7c00-4f2d-11ea-89f1-216970a73f68.png)

**Comment by Avn1114** [comment]
Aha. I've seen that in the past when I was looking. I was leaning toward using `game.world.zones` for this type of stuff. Thanks!

**Comment by Avn1114** [comment]
So I want to ask something about `world.zones`... I saw your zones and there was one that confused me. I'll explain.  
`object house
**_object toyzone_**
object shipwreck_shore`
What is "Toyzone" exactly?

**Comment by PatheticMustan** [comment]
It's that tiny island at the top right of the map, you can teleport to it with
```
PIXI.game.prodigy.debugMisc.tp("toyzone-B2")
```

and you can check your current map with

```
PIXI.game.prodigy.world.currentMap
```

If the map is not valid, you'll instead be teleported to your house.

**Comment by Avn1114** [comment]
Oh, the epics subspace.
