### ISSUE TITLE
Secret debug world in Prodigy/coming soon areas

### ISSUE THREAD

**Issue by kaddisemu** [PatheticMustan/ProdigyMathGameHacking#83]
I was wondering if there was a way to teleport into any building in Prodigy, because there are buildings in Lamplight Town that are not accessible to the public, due to the fact that they are coming in the next update. Is there a hack to access these buildings?

Also I found out that there is a debug world in prodigy in the games code. This was used by devs to test features. Is there a hack to get into the debug world?

**Comment by Avn1114** [comment]
Do you have any knowledge on how to find this “debug world”?

Sent from Mail for Windows 10

From: kaddisemu
Sent: Friday, March 20, 2020 5:14 PM
To: PatheticMustan/ProdigyMathGameHacking
Cc: Subscribed
Subject: [PatheticMustan/ProdigyMathGameHacking] Secret debug world inProdigy/coming soon areas (#83)

I was wondering if there was a way to teleport into any building in Prodigy, because there are buildings in Lamplight Town that are not accessible to the public, due to the fact that they are coming in the next update. Is there a hack to access these buildings?
Also I found out that there is a debug world in prodigy in the games code. This was used by devs to test features. Is there a hack to get into the debug world?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
This email has been checked for viruses by AVG.
https://www.avg.com

**Comment by Diveodile** [comment]
I heard something new's coming to Prodigy, it said something about: "Crystal Caverns," and there are also two buildings in Lamplight Town that says "Coming Soon" when you click on them and I want to see what these buildings are.

**Comment by Diveodile** [comment]
https://gist.github.com/Diveodile/8f4b41b5181b5cdb380581de59c84f61

**Comment by kaddisemu** [comment]
> Do you have any knowledge on how to find this “debug world”? Sent from Mail for Windows 10 From: kaddisemu Sent: Friday, March 20, 2020 5:14 PM To: PatheticMustan/ProdigyMathGameHacking Cc: Subscribed Subject: [PatheticMustan/ProdigyMathGameHacking] Secret debug world inProdigy/coming soon areas (#83) I was wondering if there was a way to teleport into any building in Prodigy, because there are buildings in Lamplight Town that are not accessible to the public, due to the fact that they are coming in the next update. Is there a hack to access these buildings? Also I found out that there is a debug world in prodigy in the games code. This was used by devs to test features. Is there a hack to get into the debug world? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> […](#)
> -- This email has been checked for viruses by AVG. https://www.avg.com
Its either in PIXI.game.prodigy.debugMisc or PIXI.game.prodigy.world. I'll have to do some digging later on :)

**Comment by kaddisemu** [comment]
> I heard something new's coming to Prodigy, it said something about: "Crystal Caverns," and there are also two buildings in Lamplight Town that says "Coming Soon" when you click on them and I want to see what these buildings are.

 Yes me too, I think it is probably the same way on how to teleport to other worlds. What I would do is use Wills Cheat Menu, go to Lamplight town and keep teleporting to locations in there. If not then use codes that arent listed.

**Comment by PatheticMustan** [comment]
You can only teleport to places that have been loaded into the client. Because the "secret crystal caverns" aren't loaded into the client, you cannot teleport into them.

**Comment by Diveodile** [comment]
Oh okay, thanks for telling us!
